### ISSUE TITLE
How to handle generic handlers

### ISSUE THREAD

**Issue by MrLotU** [tomerd/swift-server-metrics-api-proposal#15]
Hi! I should have probably posted this during the review process on the forums, but only realized it today when trying to implement this into my own Prometheus library.

Right now, all of my handlers (Counter, Gauge, Histogram & Summary) are up to an extent, generic over the type they observe. 
(From here on taking Counter as an example)
See [here](https://github.com/MrLotU/SwiftPrometheus/blob/master/Sources/Prometheus/MetricTypes/Counter.swift#L4). What this allows me to do is to have a Counter counting `Int`s, but also have a counter counting `Double`s. With the current implementation of this proposal, this is not possible and the only type coming in is `Int64`. It is of course always possible to convert a `Int64` to whatever `Numeric` type my Counter is generic over, but I'd rather not do that if there are other possibilities.

Say you want to, for some reason, expose the average of something. In many cases this will be some non Integer value. This would greatly limit the flexibility of the Counter.

I can see two possible solutions to this:
1. I change my counters to be non generic, and we don't use Integers anywhere but always use Doubles since they allow for the most precision, and biggest values (Compared to the current Int64).
2. We make the entire Metrics library generic.

I'm heavily in favor of option 1 because I gave option 2 a quick try and (with my quick implementation) you need type specifications and force casts everywhere.

Please let me know what you think though! 😄

**Comment by ktoso** [comment]
Thanks a lot for looking into adopting the API :-)

Option 1 sounds viable, I think. So no changes in the API, and your library can select the storage to be Doubles since it seems Prometheus libraries do this.

And while I'm (personally) not a fan of "store everything in doubles" (`0.1 + 0.2 = 0.30000000000000004` anyone? 🤕) it seems indeed that that's what most prometheus (at least) implementations do internally (I've checked out Go and Java some time ago). 

Option 2 I'd expect to add significant complexity, and I'd say we want to avoid that here, as this API is really just the "bare minimum."

--- 

If end users have some use case where they'd want to use metrics more specific to given backend (e.g. Double counters, if you provided them) they could do so via `SpecificLibraryMetrics` trick* we had discussed on the forums.

You could in your factory emit a counter that also accepts doubles if that's what you want, right?


---

<code>*</code> the "trick", that implementors can provide 

```swift
extension MetricsSystem {
    public static var Prometheus: PrometheusMetricsFactory {
        self.factory // ... you know the drill
    }
}

(Prometheus.counter(...): PrometheusCounter).add(2.0) // if users somehow get an PrometheusCounter they can do what you want.
```

**Comment by MrLotU** [comment]
Agreed. What I'm doing now, but might change in the future, is I'm keeping my generic metrics, but when created through the MetricsSystem, they'll be generic over whatever type the factory function takes in. So if you take `Counter` it has the function: 
```swift
func increment(_ value: Int64)
```
so when creating a counter through `makeCounter(label:dimensions:)` I'll create a `PrometheusCounter<Int64>`.

Users could than indeed use `MetricsSystem.prometheus().createCounter(forType:)` if they need something specific :)

I will close this issue because the generics issue specifically is fixed, and the discussion about using Doubles/Integers can continue in #16

**Comment by tomerd** [comment]
@MrLotU thank you for your feedback, would love to see your implementations as we transition this API to the sandbox level and can continue to iterate together

**Comment by tomerd** [comment]
@MrLotU lets move further discussions / ideas to https://github.com/apple/swift-metrics
